# Backend
FROM node:18-alpine AS backend
WORKDIR /app/backend
COPY backend/package*.json ./
RUN npm install
COPY backend/ .
ENV PORT=3001

# Frontend
FROM node:18-alpine AS frontend
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
RUN npm run build

# Final Image
FROM node:18-alpine
WORKDIR /app
COPY --from=backend /app/backend .
COPY --from=frontend /app/frontend/build ./frontend/build
EXPOSE 3001
CMD ["node", "server.js"]